# Generated by Django 5.0.6 on 2024-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biznews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_image', models.TextField(max_length=200)),
                ('biz_date', models.TextField(max_length=200)),
                ('biz_title', models.TextField(max_length=200)),
            ],
        ),
    ]
