# Generated by Django 5.0.6 on 2024-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biznews',
            name='biz_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='biznews',
            name='biz_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
