# Generated by Django 5.0.6 on 2024-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrome', '0002_alter_biznews_biz_date_alter_biznews_biz_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_image', models.ImageField(blank=True, upload_to='images/')),
                ('do_date', models.DateField(max_length=200)),
                ('do_title', models.TextField(max_length=200)),
            ],
        ),
    ]
