# Generated by Django 5.0.6 on 2024-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrome', '0003_doler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_title', models.TextField(max_length=200)),
            ],
        ),
    ]
